## Sample enablement properties file.
# [Prefix].[FlowName].[State].enabled=true|false
# [Prefix].[FlowName].[State].[Transition].enabled=true|false
# [Prefix].[FlowName].[State].meta.[key]=[value]
# [Prefix].[FlowName].[State].[Transition].meta.[key]=[value]
# [Prefix].state.add.[State].in=[FlowName]
# [Prefix].[FlowName].[State].transition.add.to.[NewState]=[Transition]
Order.order-flow.CREATED.enabled=true
