package com.homebase.ecom.promo.model;

import org.chenile.workflow.activities.model.ActivityEnabledStateEntity;
import org.chenile.workflow.activities.model.ActivityLog;
import java.util.*;
import java.time.LocalDateTime;
import org.chenile.workflow.model.*;
import jakarta.persistence.*;
import org.chenile.jpautils.entity.AbstractJpaStateEntity;

/**
 * Promo entity managed by the STM.
 *
 * Item 11 fields: id, code, name, description, discountType, discountValue,
 * minOrderValue, maxDiscountAmount, startDate, endDate, usageLimit, usageCount,
 * usagePerCustomer, applicableCategories, applicableProducts, stateId, flowId.
 *
 * Uses String id from BaseJpaEntity (auto-generated by IDGenerator).
 * Removed: order details, customer details, cart details (those belong in Order/Cart BCs).
 */
@Entity
@Table(name = "coupon")
public class Coupon extends AbstractJpaStateEntity
        implements ActivityEnabledStateEntity, ContainsTransientMap {

    @Column(name = "code", unique = true, nullable = false)
    private String code;

    @Column(name = "name", nullable = false)
    private String name;

    @Column(name = "description")
    private String description;

    /**
     * PERCENTAGE, FLAT, BUY_X_GET_Y
     */
    @Column(name = "discount_type", nullable = false)
    private String discountType;

    @Column(name = "discount_value", nullable = false)
    private Double discountValue;

    @Column(name = "min_order_value")
    private Double minOrderValue;

    @Column(name = "max_discount_amount")
    private Double maxDiscountAmount;

    @Column(name = "start_date")
    private LocalDateTime startDate;

    @Column(name = "end_date")
    private LocalDateTime endDate;

    /**
     * Maximum total uses across all customers.
     */
    @Column(name = "usage_limit")
    private Integer usageLimit = 0;

    /**
     * Current total usage count.
     */
    @Column(name = "usage_count")
    private Integer usageCount = 0;

    /**
     * Max uses per individual customer.
     */
    @Column(name = "usage_per_customer")
    private Integer usagePerCustomer = 1;

    @org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.JSON)
    @Column(columnDefinition = "jsonb", name = "applicable_categories")
    private List<String> applicableCategories = new ArrayList<>();

    @org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.JSON)
    @Column(columnDefinition = "jsonb", name = "applicable_products")
    private List<String> applicableProducts = new ArrayList<>();

    @Transient
    public TransientMap transientMap = new TransientMap();

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
    @JoinColumn(name = "promo_code")
    public List<PromoCodeActivityLog> activities = new ArrayList<>();

    // --- Business Logic Methods ---

    public boolean isSingleUsePerCustomer() {
        return usagePerCustomer != null && usagePerCustomer == 1;
    }

    public boolean isValid() {
        return isInActiveState() && !isExpired() && !isUsageLimitReached();
    }

    public boolean isInActiveState() {
        return getCurrentState() != null && "ACTIVE".equalsIgnoreCase(getCurrentState().getStateId());
    }

    public boolean isExpired() {
        return endDate != null && endDate.isBefore(LocalDateTime.now());
    }

    public boolean isStartDateReached() {
        return startDate == null || !startDate.isAfter(LocalDateTime.now());
    }

    public boolean isMinOrderMet(double cartTotal) {
        return minOrderValue == null || cartTotal >= minOrderValue;
    }

    public boolean isUsageLimitReached() {
        return usageLimit != null && usageLimit > 0 && usageCount != null && usageCount >= usageLimit;
    }

    public void incrementUsage() {
        if (usageCount == null) usageCount = 0;
        usageCount++;
    }

    public boolean appliesTo(String productId, String categoryId) {
        if ((applicableProducts == null || applicableProducts.isEmpty()) &&
                (applicableCategories == null || applicableCategories.isEmpty())) {
            return true;
        }
        if (applicableProducts != null && applicableProducts.contains(productId)) {
            return true;
        }
        if (applicableCategories != null && applicableCategories.contains(categoryId)) {
            return true;
        }
        return false;
    }

    public double calculateDiscount(double amount) {
        double discount = 0;
        if ("PERCENTAGE".equalsIgnoreCase(discountType)) {
            discount = amount * (discountValue / 100.0);
            if (maxDiscountAmount != null && discount > maxDiscountAmount) {
                discount = maxDiscountAmount;
            }
        } else if ("FLAT".equalsIgnoreCase(discountType)) {
            discount = Math.min(amount, discountValue);
        }
        // BUY_X_GET_Y logic handled in strategy layer
        return discount;
    }

    // --- Getters and Setters ---

    public String getCode() { return code; }
    public void setCode(String code) { this.code = code; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getDiscountType() { return discountType; }
    public void setDiscountType(String discountType) { this.discountType = discountType; }

    public Double getDiscountValue() { return discountValue; }
    public void setDiscountValue(Double discountValue) { this.discountValue = discountValue; }

    public Double getMinOrderValue() { return minOrderValue; }
    public void setMinOrderValue(Double minOrderValue) { this.minOrderValue = minOrderValue; }

    public Double getMaxDiscountAmount() { return maxDiscountAmount; }
    public void setMaxDiscountAmount(Double maxDiscountAmount) { this.maxDiscountAmount = maxDiscountAmount; }

    public LocalDateTime getStartDate() { return startDate; }
    public void setStartDate(LocalDateTime startDate) { this.startDate = startDate; }

    public LocalDateTime getEndDate() { return endDate; }
    public void setEndDate(LocalDateTime endDate) { this.endDate = endDate; }

    public Integer getUsageLimit() { return usageLimit; }
    public void setUsageLimit(Integer usageLimit) { this.usageLimit = usageLimit; }

    public Integer getUsageCount() { return usageCount; }
    public void setUsageCount(Integer usageCount) { this.usageCount = usageCount; }

    public Integer getUsagePerCustomer() { return usagePerCustomer; }
    public void setUsagePerCustomer(Integer usagePerCustomer) { this.usagePerCustomer = usagePerCustomer; }

    public List<String> getApplicableCategories() { return applicableCategories; }
    public void setApplicableCategories(List<String> applicableCategories) { this.applicableCategories = applicableCategories; }

    public List<String> getApplicableProducts() { return applicableProducts; }
    public void setApplicableProducts(List<String> applicableProducts) { this.applicableProducts = applicableProducts; }

    @Override
    public TransientMap getTransientMap() { return this.transientMap; }
    public void setTransientMap(TransientMap transientMap) { this.transientMap = transientMap; }

    @Override
    public Collection<ActivityLog> obtainActivities() { return new ArrayList<>(activities); }

    @Override
    public ActivityLog addActivity(String eventId, String comment) {
        PromoCodeActivityLog activityLog = new PromoCodeActivityLog();
        activityLog.setActivityName(eventId);
        activityLog.setActivityComment(comment);
        activityLog.setActivitySuccess(true);
        activities.add(activityLog);
        return activityLog;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Coupon)) return false;
        if (!super.equals(o)) return false;
        Coupon coupon = (Coupon) o;
        return Objects.equals(getId(), coupon.getId()) &&
                Objects.equals(code, coupon.code);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), getId(), code);
    }
}
