apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml

images:
  - name: homebase-shipping
    newName: ${ECR_REGISTRY}/homebase-shipping
    newTag: latest

patchesStrategicMerge:
  - replica-patch.yaml
