apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: shipping
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: shipping
spec:
  replicas: 3
