## Enablement properties for Banner STM
# [Prefix].[FlowName].[State].enabled=true|false
# [Prefix].[FlowName].[State].[Transition].enabled=true|false
Banner.banner-flow.DRAFT.enabled=true
Banner.banner-flow.DRAFT.activate=true
Banner.banner-flow.DRAFT.schedule=true
Banner.banner-flow.SCHEDULED.enabled=true
Banner.banner-flow.SCHEDULED.activate=true
Banner.banner-flow.SCHEDULED.deactivate=true
Banner.banner-flow.ACTIVE.enabled=true
Banner.banner-flow.ACTIVE.deactivate=true
Banner.banner-flow.ACTIVE.expire=true
Banner.banner-flow.EXPIRED.enabled=true
Banner.banner-flow.EXPIRED.activate=true
