apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: keycloak
          args:
            - start
            - --import-realm
            - --optimized
          env:
            - name: KC_HOSTNAME
              value: auth-sit.homebase.com
            - name: KC_HOSTNAME_STRICT
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "false"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
