apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: product
  labels:
    app.kubernetes.io/name: product
    app.kubernetes.io/part-of: homebase
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: product
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
