apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebase-ingress
  namespace: homebase
  labels:
    app.kubernetes.io/part-of: homebase
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: homebase.local
      http:
        paths:
          - path: /api/product(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product
                port:
                  number: 8080
          - path: /api/inventory(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: inventory
                port:
                  number: 8080
          - path: /api/order(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: order
                port:
                  number: 8080
          - path: /api/cart(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cart
                port:
                  number: 8080
          - path: /api/shipping(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: shipping
                port:
                  number: 8080
          - path: /api/payment(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: payment
                port:
                  number: 8080
          - path: /api/user(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user
                port:
                  number: 8080
          - path: /api/supplier(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: supplier
                port:
                  number: 8080
          - path: /auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
