# All Chenile configuration properties
chenile.security.ignore=true
chenile.query.proxy.enabled=true
chenile.query.remote.base-url=http://localhost:8081/
chenile.base.url=http://localhost:8081
chenile.service.json.package=classpath*:com/homebase/ecom/**/service/*.json,classpath*:org/chenile/**/service/*.json
chenile.module.name=catalog
chenile.pre.processors=populateContextContainer
