apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-configmap
  namespace: config-server
data:
  CONFIG_REPO_URI: "https://github.com/homebase-ecom/config-repo"
  CONFIG_REPO_BRANCH: "main"
  SPRING_PROFILES_ACTIVE: "git"
