apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: checkout
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/part-of: homebase
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: checkout
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
