server:
  port: 8085

spring:
  application:
    name: policy-service
  datasource:
    url: jdbc:h2:mem:policydb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

chenile:
  base:
    url: http://localhost:${server.port}
  stm:
    definition: classpath:stm/policy-lifecycle.xml

