apiVersion: v1
kind: Service
metadata:
  name: supplier
  namespace: supplier
  labels:
    app.kubernetes.io/name: supplier
    app.kubernetes.io/part-of: homebase
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supplier
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
