## Enablement properties for Return Request STM
# [Prefix].[FlowName].[State].enabled=true|false
# [Prefix].[FlowName].[State].[Transition].enabled=true|false
Returnrequest.return-request-flow.REQUESTED.enabled=true
