apiVersion: v1
kind: Service
metadata:
  name: rules-engine
  namespace: rules-engine
  labels:
    app.kubernetes.io/name: rules-engine
    app.kubernetes.io/part-of: homebase
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rules-engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
