apiVersion: v1
kind: Service
metadata:
  name: offer
  namespace: offer
  labels:
    app.kubernetes.io/name: offer
    app.kubernetes.io/part-of: homebase
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: offer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
