## Enablement properties for Announcement STM
# [Prefix].[FlowName].[State].enabled=true|false
# [Prefix].[FlowName].[State].[Transition].enabled=true|false
Announcement.announcement-flow.DRAFT.enabled=true
Announcement.announcement-flow.DRAFT.schedule=true
Announcement.announcement-flow.DRAFT.activate=true
Announcement.announcement-flow.SCHEDULED.enabled=true
Announcement.announcement-flow.SCHEDULED.activate=true
Announcement.announcement-flow.SCHEDULED.deactivate=true
Announcement.announcement-flow.ACTIVE.enabled=true
Announcement.announcement-flow.ACTIVE.expire=true
Announcement.announcement-flow.ACTIVE.deactivate=true
Announcement.announcement-flow.EXPIRED.enabled=true
Announcement.announcement-flow.EXPIRED.activate=true
