## User enablement properties
# [Prefix].[FlowName].[State].enabled=true|false
# [Prefix].[FlowName].[State].[Transition].enabled=true|false
User.user-flow.REGISTERED.enabled=true
User.user-flow.EMAIL_VERIFIED.enabled=true
User.user-flow.ACTIVE.enabled=true
User.user-flow.LOCKED.enabled=true
User.user-flow.SUSPENDED.enabled=true
User.user-flow.DEACTIVATED.enabled=true
User.user-flow.KYC_PENDING.enabled=true
User.user-flow.KYC_VERIFIED.enabled=true
