package com.homebase.ecom.promo.model;

import org.chenile.workflow.activities.model.ActivityEnabledStateEntity;
import org.chenile.workflow.activities.model.ActivityLog;
import java.util.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import org.chenile.workflow.model.*;
import jakarta.persistence.*;
import org.chenile.jpautils.entity.AbstractJpaStateEntity;

/**
 * Campaign entity managed by the STM.
 *
 * Types: FLASH_SALE, SEASONAL, CLEARANCE, BOGO, FESTIVAL
 * Uses String id from BaseJpaEntity (auto-generated by IDGenerator).
 */
@Entity
@Table(name = "campaign")
public class Campaign extends AbstractJpaStateEntity
        implements ActivityEnabledStateEntity, ContainsTransientMap {

    @Column(name = "name", nullable = false)
    private String name;

    /**
     * FLASH_SALE, SEASONAL, CLEARANCE, BOGO, FESTIVAL
     */
    @Column(name = "campaign_type")
    private String campaignType;

    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * PERCENTAGE, FIXED_AMOUNT
     */
    @Column(name = "discount_type")
    private String discountType;

    @Column(name = "discount_value", precision = 12, scale = 2)
    private BigDecimal discountValue;

    @Column(name = "start_date")
    private LocalDateTime startDate;

    @Column(name = "end_date")
    private LocalDateTime endDate;

    @Column(name = "budget", precision = 15, scale = 2)
    private BigDecimal budget;

    @Column(name = "spent", precision = 15, scale = 2)
    private BigDecimal spent = BigDecimal.ZERO;

    @Column(name = "revenue", precision = 15, scale = 2)
    private BigDecimal revenue = BigDecimal.ZERO;

    @Column(name = "usage_count")
    private Integer usageCount = 0;

    /**
     * Comma-separated list of applicable category IDs.
     */
    @Column(name = "applicable_categories", columnDefinition = "TEXT")
    private String applicableCategoriesCsv;

    /**
     * Comma-separated list of applicable product IDs.
     */
    @Column(name = "applicable_products", columnDefinition = "TEXT")
    private String applicableProductsCsv;

    @Column(name = "min_order_amount", precision = 12, scale = 2)
    private BigDecimal minOrderAmount;

    @Column(name = "max_discount_amount", precision = 12, scale = 2)
    private BigDecimal maxDiscountAmount;

    @Transient
    public TransientMap transientMap = new TransientMap();

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
    @JoinColumn(name = "campaign_id")
    public List<CampaignActivityLog> activities = new ArrayList<>();

    // --- Business Logic Methods ---

    public boolean isActive() {
        return getCurrentState() != null && "ACTIVE".equalsIgnoreCase(getCurrentState().getStateId());
    }

    public boolean isExpired() {
        return endDate != null && endDate.isBefore(LocalDateTime.now());
    }

    public boolean isStartDateReached() {
        return startDate == null || !startDate.isAfter(LocalDateTime.now());
    }

    public boolean isBudgetExhausted() {
        return budget != null && spent != null && spent.compareTo(budget) >= 0;
    }

    public BigDecimal getRemainingBudget() {
        if (budget == null) return null;
        if (spent == null) return budget;
        return budget.subtract(spent);
    }

    public void incrementUsage() {
        if (usageCount == null) usageCount = 0;
        usageCount++;
    }

    public void addSpent(BigDecimal amount) {
        if (spent == null) spent = BigDecimal.ZERO;
        spent = spent.add(amount);
    }

    public void addRevenue(BigDecimal amount) {
        if (revenue == null) revenue = BigDecimal.ZERO;
        revenue = revenue.add(amount);
    }

    public List<String> getApplicableCategories() {
        if (applicableCategoriesCsv == null || applicableCategoriesCsv.isBlank()) return new ArrayList<>();
        return new ArrayList<>(Arrays.asList(applicableCategoriesCsv.split(",")));
    }

    public void setApplicableCategories(List<String> applicableCategories) {
        this.applicableCategoriesCsv = (applicableCategories == null || applicableCategories.isEmpty())
                ? null : String.join(",", applicableCategories);
    }

    public List<String> getApplicableProducts() {
        if (applicableProductsCsv == null || applicableProductsCsv.isBlank()) return new ArrayList<>();
        return new ArrayList<>(Arrays.asList(applicableProductsCsv.split(",")));
    }

    public void setApplicableProducts(List<String> applicableProducts) {
        this.applicableProductsCsv = (applicableProducts == null || applicableProducts.isEmpty())
                ? null : String.join(",", applicableProducts);
    }

    // --- Getters and Setters ---

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getCampaignType() { return campaignType; }
    public void setCampaignType(String campaignType) { this.campaignType = campaignType; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getDiscountType() { return discountType; }
    public void setDiscountType(String discountType) { this.discountType = discountType; }

    public BigDecimal getDiscountValue() { return discountValue; }
    public void setDiscountValue(BigDecimal discountValue) { this.discountValue = discountValue; }

    public LocalDateTime getStartDate() { return startDate; }
    public void setStartDate(LocalDateTime startDate) { this.startDate = startDate; }

    public LocalDateTime getEndDate() { return endDate; }
    public void setEndDate(LocalDateTime endDate) { this.endDate = endDate; }

    public BigDecimal getBudget() { return budget; }
    public void setBudget(BigDecimal budget) { this.budget = budget; }

    public BigDecimal getSpent() { return spent; }
    public void setSpent(BigDecimal spent) { this.spent = spent; }

    public BigDecimal getRevenue() { return revenue; }
    public void setRevenue(BigDecimal revenue) { this.revenue = revenue; }

    public Integer getUsageCount() { return usageCount; }
    public void setUsageCount(Integer usageCount) { this.usageCount = usageCount; }

    public BigDecimal getMinOrderAmount() { return minOrderAmount; }
    public void setMinOrderAmount(BigDecimal minOrderAmount) { this.minOrderAmount = minOrderAmount; }

    public BigDecimal getMaxDiscountAmount() { return maxDiscountAmount; }
    public void setMaxDiscountAmount(BigDecimal maxDiscountAmount) { this.maxDiscountAmount = maxDiscountAmount; }

    @Override
    public TransientMap getTransientMap() { return this.transientMap; }
    public void setTransientMap(TransientMap transientMap) { this.transientMap = transientMap; }

    public List<CampaignActivityLog> getActivities() { return activities; }
    public void setActivities(List<CampaignActivityLog> activities) { this.activities = activities; }

    @Override
    public Collection<ActivityLog> obtainActivities() { return new ArrayList<>(activities); }

    @Override
    public ActivityLog addActivity(String eventId, String comment) {
        CampaignActivityLog activityLog = new CampaignActivityLog();
        activityLog.setEventId(eventId);
        activityLog.setComment(comment);
        activityLog.setSuccess(true);
        activities.add(activityLog);
        return activityLog;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Campaign)) return false;
        if (!super.equals(o)) return false;
        Campaign campaign = (Campaign) o;
        return Objects.equals(getId(), campaign.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), getId());
    }
}
