## Enablement properties for CMS Page STM
# [Prefix].[FlowName].[State].enabled=true|false
# [Prefix].[FlowName].[State].[Transition].enabled=true|false
CmsPage.cms-page-flow.DRAFT.enabled=true
CmsPage.cms-page-flow.DRAFT.submitForReview=true
CmsPage.cms-page-flow.DRAFT.publish=true
CmsPage.cms-page-flow.IN_REVIEW.enabled=true
CmsPage.cms-page-flow.IN_REVIEW.approve=true
CmsPage.cms-page-flow.IN_REVIEW.reject=true
CmsPage.cms-page-flow.PUBLISHED.enabled=true
CmsPage.cms-page-flow.PUBLISHED.unpublish=true
CmsPage.cms-page-flow.PUBLISHED.archive=true
CmsPage.cms-page-flow.ARCHIVED.enabled=true
CmsPage.cms-page-flow.ARCHIVED.restore=true
