apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: user
spec:
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: app
          image: homebase/user-app
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
