apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: user
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/part-of: homebase
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
